---
services:
  pr:
    image: pr:latest
    build:
      context: .
      args:
        D4R6Y: ${D4R6Y}
        PIP_CONF: ${PIP_CONF}
        APK_ARGS: ${APK_ARGS}
    ports:
      - 8080:8080
    environment:
      # See https://docs.sqlalchemy.org/en/20/core/engines.html#postgresql
      - PR_DATABASE_URL=postgresql+psycopg2://admin:SuperSecret@postgres/testdb
      - PR_CUSTO_FILENAME=/custo/custo.yaml
      - TZ=Europe/Paris
    volumes:
      - ./tests/:/custo
    depends_on:
      - postgres
    links:
      - postgres
    restart: on-failure
  postgres:
    image: ${D4R6Y}postgres:18.4-alpine3.24
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=SuperSecret
      - TZ=Europe/Paris
  # pgadmin:
  #   image: ${D4R6Y}dpage/pgadmin4:2026-06-18-3
  #   ports:
  #     - 9080:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=osia@secureidentityalliance.org
  #     - PGADMIN_DEFAULT_PASSWORD=OSIASecret
