[tox]
envlist = clean,py,mon,tls
# [---CUSTO---]
    pg
# [---CUSTO---]
    report

[testenv]
usedevelop = true
deps =
    coverage
    pytest
    requests
# [---CUSTO---]
    requests-toolbelt
# [---CUSTO---]
setenv =
    PR_CONF_DIR=tests/conf
    SQLITE=1
    PR_CUSTO_FILENAME={work_dir}/../tests/custo.yaml
# [---CUSTO---]
# [---CUSTO---]
commands =
    coverage run -a --source=src -m pytest -s .

[testenv:tls]
setenv =
    PR_CONF_DIR=tests/conf
    PR_SERVER_CERTFILE=tests/TLS_CA/server.pem
    PR_SERVER_KEYFILE=tests/TLS_CA/server.key
    PR_SERVER_KEYFILE_PASSWORD=secret
    SQLITE=1
    PR_CUSTO_FILENAME={work_dir}/../tests/custo.yaml
# [---CUSTO---]
# [---CUSTO---]
commands =
    coverage run -a --source=src -m pytest -s tests/test_pr.py

[testenv:mon]
setenv =
    PR_MONITORING_PORT=9090
    SQLITE=1
    PR_CUSTO_FILENAME={work_dir}/../tests/custo.yaml
# [---CUSTO---]
# [---CUSTO---]
commands =
    coverage run -a --source src -m pytest -s tests/test_monitoring.py

[tool:pytest]
cache_dir=.tox/pytest-cache

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase

[testenv:report]
deps = coverage
skip_install = true
commands =
    coverage report
    coverage xml
    coverage html

# [---CUSTO---]
[testenv:pg]
deps =
    coverage
    pytest
    requests
    requests-toolbelt
    psycopg2-binary
    asyncpg
setenv =
    PR_CONF_DIR=tests/conf
    PR_CUSTO_FILENAME={work_dir}/../tests/custo.yaml
    PR_DATABASE_URL=postgresql+psycopg2://admin:SuperSecret@localhost/plug2db
    SQLITE=0

commands =
    coverage run -a --source=src -m pytest -s tests/test_pr.py
# [---CUSTO---]