CREATE SCHEMA pr;
CREATE USER pr LOGIN PASSWORD 'PRSecret' CONNECTION LIMIT 50;
GRANT ALL ON SCHEMA pr TO pr;

CREATE SCHEMA enrollment;
CREATE USER enrollment LOGIN PASSWORD 'EnrollmentSecret' CONNECTION LIMIT 50;
GRANT ALL ON SCHEMA enrollment TO enrollment;
