FROM alpine:3.17.3

RUN apk add tzdata
ENV TZ=Europe/Paris

RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY src/ ./
ENTRYPOINT [".py/bin/python", "-m", "uin"]

