---
app: enrollment
mod: server
author: Olivier Heurtier
author_email: olivier.heurtier@secureidentityalliance.org
license: Apache 2.0
clients:
  - notification
sql:
  getters:
    enrollment: Enrollment
  gauges:
    enrollments: Enrollment
    biometricdata: BiometricData
    buffers: Buffer
entity: Enrollment
openapi: 1
