[tox]
envlist = clean,py,mon,tls
# [---CUSTO---]
    pg
# [---CUSTO---]
    report

[testenv]
usedevelop = true
deps =
    coverage
    gevent
    pytest
    requests
# [---CUSTO---]
# [---CUSTO---]
setenv =
    ENROLLMENT_CONF_DIR=tests/conf
    SQLITE=1
    ENROLLMENT_CUSTO_FILENAME={work_dir}/../tests/custo.yaml
# [---CUSTO---]
# [---CUSTO---]
commands =
    coverage run -a --source=src -m pytest -s .

[testenv:tls]
setenv =
    ENROLLMENT_CONF_DIR=tests/conf
    ENROLLMENT_SERVER_CERTFILE=tests/TLS_CA/server.pem
    ENROLLMENT_SERVER_KEYFILE=tests/TLS_CA/server.key
    ENROLLMENT_SERVER_KEYFILE_PASSWORD=secret
    SQLITE=1
    ENROLLMENT_CUSTO_FILENAME={work_dir}/../tests/custo.yaml
# [---CUSTO---]
    ENROLLMENT_NOTIFICATION_URL=https://localhost:8080
    ENROLLMENT_NOTIFICATION_CA_CERTFILE=tests/TLS_CA/server.pem
# [---CUSTO---]
commands =
    coverage run -a --source=src -m pytest -s tests/test_enrollment.py

[testenv:mon]
setenv =
    ENROLLMENT_MONITORING_PORT=9090
    SQLITE=1
    ENROLLMENT_CUSTO_FILENAME={work_dir}/../tests/custo.yaml
# [---CUSTO---]
# [---CUSTO---]
commands =
    coverage run -a --source src -m pytest -s tests/test_monitoring.py

[tool:pytest]
cache_dir=.tox/pytest-cache

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase

[testenv:report]
deps = coverage
skip_install = true
commands =
    coverage report
    coverage xml
    coverage html

# [---CUSTO---]
[testenv:pg]
deps =
    coverage
    gevent
    pytest
    requests
    requests-toolbelt
    psycopg2-binary
    asyncpg
setenv =
    ENROLLMENT_CONF_DIR=tests/conf
    ENROLLMENT_CUSTO_FILENAME={work_dir}/../tests/custo.yaml
    ENROLLMENT_DATABASE_URL=postgresql+psycopg2://admin:SuperSecret@postgres/testdb
    SQLITE=0

commands =
    coverage run -a --source=src -m pytest -s tests/test_enrollment.py
# [---CUSTO---]